coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        compare: false
comment:
  layout: "header"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  hide_project_coverage: false
  hide_complexity: true
  hide_files: true  # Скрыть список файлов
  hide_lines: true  # Скрыть строки с отсутствующим покрытием
  show_critical_paths: false  # Отключить показ проблемных файлов