server:
  port:
  - 8079

spring:
  cloud:
    gateway:
      routes:
      - id: STATEMENT_CREATE_STATEMENT
        uri: ${POST_STATEMENT_URI:http://localhost:9090/statement}
        predicates:
          - Path=/statement
          - Method=POST
      - id: STATEMENT_APPLY_OFFER
        uri: ${POST_STATEMENT_OFFER_URI:http://localhost:9090/statement/offer}
        predicates:
        - Path=/statement/offer/**
        - Method=POST

      - id: DEAL_CALCULATE_CREDIT
        uri: ${POST_CALCULATE_CREDIT_URI:http://localhost:7070/deal/calculate}
        predicates:
          - Path=/deal/calculate/{statementId}
          - Method=POST
        filters:
          - AddRequestParameter=statementId, {statementId}
      - id: DEAL_SEND_DOCUMENTS
        uri: ${POST_SEND_DOCUMENTS_URI:http://localhost:7070/deal/document/{statementId}/send}
        predicates:
          - Path=/deal/document/{statementId}/send
          - Method=POST
      - id: DEAL_SIGN_DOCUMENTS
        uri: ${POST_SIGN_DOCUMENTS_URI:http://localhost:7070/deal/document/{statementId}/sign}
        predicates:
          - Path=/deal/document/{statementId}/sign
          - Method=POST

      - id: DEAL_VERIFY_SES_CODE
        uri: ${POST_VERIFY_SES_CODE_URI:http://localhost:7070/deal/document/{statementId}/code}
        predicates:
          - Path=/deal/document/{statementId}/code
          - Method=POST



