name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181

      kafka:
        image: bitnami/kafka:latest
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
          ALLOW_PLAINTEXT_LISTENER: "yes"
        ports:
          - 9093:9093

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Debug Kafka logs
        run: docker ps -a && docker logs $(docker ps -aq --filter "name=kafka")

      - name: Wait for Kafka to start
        run: sleep 15

      - name: Clean, test, verify
        run: mvn clean verify

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker-Compose
        run: docker-compose up -d --build

      - name: Wait for healthy state
        run: |
          echo "Waiting for services to be healthy..."
          docker-compose wait

      - name: Stop Docker-Compose
        run: docker-compose down --volumes